name: deploy-taas

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy TaaS App
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Sleep for 20 seconds
      run: sleep 200

    - name: Build Docker image
      run: |
        docker build -t taas-sample:latest .

    - name: Run container
      run: |
        docker run -d --rm --name taas-test -p 8080:80 taas-sample:latest

    - name: Wait and test container
      run: |
        sleep 5
        curl -I http://localhost:8080 || true

    - name: Clean up container
      if: always()
      run: |
        docker stop taas-test || true
